site_name: samesame
site_description: Samesame - Classifier Two-sample Tests

nav:
  - Home: index.md
  - Examples:
    - Distribution shifts: examples/distribution-shifts.md
    - Noninferiority tests: examples/noninferiority.md
  - API:
      - bayes: api/bayes.md
      - ctst: api/ctst.md
      - nit: api/nit.md
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
theme:
  name: material
  icon:
    logo: fontawesome/solid/check-double
    favicon: fontawesome/solid/check-double
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.expand
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js